blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='blog.home_view'),
    path('p/<str:slug>/', views.PostDetailView.as_view(), name='blog.post_view'),
    path('random/', views.random_post, name='blog.random_post'),
    path('all', views.AllPostsView.as_view(), name='blog.all_posts'),
    path('new/', views.PostCreateView.as_view(), name='blog.new'),
    path('edit/<str:slug>/', views.PostUpdateView.as_view(), name='blog.edit'), 
]

levlog/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog'), name='levlog.index'),  # temp
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models/category.py
from django.db import models
from django.utils.translation import gettext as _



class Category(models.Model):
    name = models.CharField(max_length=100)
    image_svg = models.FileField(
        upload_to='category_images/', 
        verbose_name=_('image'),
    )

    def __str__(self) -> str:
        return self.name.title()

    class Meta:
        verbose_name_plural = 'categories'

blog/models/post.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext as _
from tinymce.models import HTMLField
from stdimage import StdImageField


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-rating', '-created_on')


class AvaliablePostManager(PostManager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED
        )


class Post(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = (0, 'Draft')
        PUBLISHED = (1, 'Published')
        HIDDEN = (2, 'Hidden')
        DELETED = (3, 'Deleted')


    title = models.CharField(max_length=200, verbose_name=_('title'))
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('author'),
    )
    
    preview_image = StdImageField(
        upload_to='uploads/%Y/%m/%d/',
        null=True,
        variations={
            'cropped': {'width': 1000, 'height': 400, 'crop': True},
            'small': {'width': 400, 'height': 400},
            'box' : {'width': 400, 'height': 400, 'crop': True}
        },
        verbose_name=_('preview'),
    )
    updated_on = models.DateTimeField(auto_now=True, verbose_name=_('last update'))
    
    short_description = HTMLField(verbose_name=_('short'), null=True)
    emoji_description = models.CharField(max_length=256, verbose_name=_('emoji'), null=True)
    content = HTMLField(verbose_name=_('content'))

    created_on = models.DateTimeField(verbose_name=_('creation time'))
    status = models.IntegerField(choices=Status.choices, default=Status.DRAFT, verbose_name=_('status'))
    
    rating = models.IntegerField(default=1, verbose_name=_('rating'))
    category = models.ForeignKey(
        to='blog.category', 
        on_delete=models.CASCADE,
        verbose_name=_('category'),
        null=True,
        blank=True,
    )
    keywords = models.TextField(verbose_name=_('keywords'), default='')

    objects = PostManager()
    avaliable_objects = AvaliablePostManager()

    @property
    def views(self):
        """
        Amount of views is amount if unique ips that accessed that post
        """
        return PostView.objects.filter(post=self).count()

    def get_absolute_url(self):
        return reverse('blog.post_view', args=(self.slug,))

    def __str__(self):
        return f'{self.title}({self.views})'


class PostView(models.Model):
    ip = models.GenericIPAddressField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('post view')
        verbose_name_plural = _('post views')

    def __str__(self):
        return f'{self.ip} in {self.post}'

blog/models/user.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

blog/views/all_posts.py
from blog.models import Post
from django.views.generic import ListView


class AllPostsView(ListView):
    model = Post
    template_name = 'blog/all_posts.html'
    paginate_by = 3
    queryset = Post.avaliable_objects.order_by('-created_on').all()

blog/views/home.py
from blog.models import Post
from django.views.generic import ListView


class HomeView(ListView):
    model = Post
    template_name = 'blog/index.html'
    queryset = Post.avaliable_objects.all()[:5]

blog/views/post.py
from blog.models import Post, PostView
from blog.views.utils import get_client_ip

from django.views.generic import DetailView, CreateView, UpdateView
from django.shortcuts import redirect
from django.http import HttpRequest


def random_post(request):
    object = Post.avaliable_objects.order_by('?').first()
    return redirect(object)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post.html'


    def get_queryset(self):
        if self.request.user.is_staff:
            return Post.objects
        else:
            return Post.avaliable_objects
    

    def get(self, request: HttpRequest, *args, **kwargs):           
        response = super().get(request, *args, **kwargs)
        self.increase_views(request)
        return response
        
    def increase_views(self, request):
        ip = get_client_ip(request)
        if ip:
            PostView.objects.get_or_create(
                ip=ip,
                post=self.object,
            )


class PostCreateView(CreateView):
    model = Post
    fields = '__all__'
    template_name = 'blog/new.html'


class PostUpdateView(UpdateView):
    model = Post
    fields = '__all__'
    #template_name = 'blog/edit.html'

blog/views/utils.py
from django.http import HttpRequest


def get_client_ip(request: HttpRequest):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

templates/blog/all_posts.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %} 

{% for post in post_list %}

<div class="container mt-5">
      <div class="card mb-3 shadow-sm">
          <div class="row">
            <div class="col-md-8 align-self-center">
              <div class="card-body">
                <a href= "{{ post.get_absolute_url }}" class="text-dark"><h3 class="card-title font-weight-bold">{{ post.title }}</h3></a>
                <p class="card-text">{{ post.short_description | safe }}</p>
                <p class="card-text"><small class="text-dark">Posted {{ post.created_on | date:"j M" }}</small></p>
                <img src="{{ post.category.image_svg.url }}" title="Категория: {{ post.category.name }}" rel="tooltip" class="svg_small float-left">
                <p class="float-right text-muted"><img src="{% static 'blog/svg/eye.svg' %}"> {{ post.views }} </p>
              </div>
              
            </div>
            <div class="col-md-4">
              <img src="{{ post.preview_image.small.url }}" class="card-img" alt="...">
            </div>
          </div>
        </div>
    </div>
{% endfor %}

<!-- PAGINATION -->

{% if is_paginated %}
  <!--Pagination-->
    <nav aria-label="Page navigation">
      <ul class="pagination pagination-lg justify-content-center">
          <!-- Prev button -->
          <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            <a
            class="page-link" 
            href={% if page_obj.has_previous %}"?page={{ page_obj.previous_page_number }}" {% else %} "#" {% endif %}
            >Туда</a>
          </li>
  
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        <!-- Next button -->
        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
            <a
            class="page-link" 
            href={% if page_obj.has_next %}"?page={{ page_obj.next_page_number }}" {% else %} "#" {% endif %}
            >Сюда</a>
        </li>
      </ul>
    </nav>
    <!--end of Pagination-->

{% endif %}



{% endblock %}

templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.4.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    <title>levlog</title>
  </head>
  <body>
   <!-- NAVIGATION -->
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand font-weight-bold" href="{% url 'levlog.index' %}">
          <img src="{% static 'blog/img/logo.png' %}" class="img-fluid">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active mr-3">
              <a class="nav-link" href="{% url 'blog.home_view' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'blog.all_posts' %}">Posts</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'blog.random_post' %}">Random post</a>
            </li>
            <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://www.instagram.com/donotshareit/"><i class="ri-instagram-fill"></i></a>
              </li>
            <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://t.me/sevenzing"><i class="ri-telegram-fill"></i></i></a>
              </li>
              <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://github.com/sevenzing/"><i class="ri-github-fill"></i></a>
                
              </li>
          </ul>
        </div>
      </nav>
</div>

   <!-- NAVIGATION END -->
   
    {% block content %}

    {% endblock %}

    <!-- FOOTER -->
    <br><br><br><br><br>

    <footer class="text-center text-white" style="background-color: #f1f1f1;">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.instagram.com/donotshareit/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-instagram-fill"></i
          ></a>

          <!-- Telegram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://t.me/sevenzing"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-telegram-fill"></i
          ></a>

          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://github.com/sevenzing/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-github-fill"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021 Copyleft:
        <a class="text-dark" href="https://mdbootstrap.com/">levlog.kek</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(function () {
            $("[rel='tooltip']").tooltip();
        });
    </script>
  </body>
</html>

templates/blog/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}

<div class="head-section">
    <div class="container">
     <div class="{% if request.user_agent.is_mobile %}column{% else %}row{% endif %} p-5">
         <div class="col align-self-center" style="padding-left: 0px; padding-right: 0px;">
             <h1 class="font-weight-bold">Мой блог🔎</h1>
             <h2 class="text-secondary font-weight-lighter">и немного мемов</h2>
         </div>
         <div class="col align-self-center">
             <img src="{% static 'blog/img/head-img.small.png' %}" class="img-fluid">
         </div>
     </div>
    </div>
</div>
<!-- CONTENT -->

{% for post in post_list %} 
  {% if forloop.first  %}
    <div class="container mt-5">
      <div class="card mb-3 shadow-sm">
          <div class="row">
            <div class="col-md-8 align-self-center">
              <div class="card-body">
                <a href= "{{ post.get_absolute_url }}" class="text-dark"><h3 class="card-title font-weight-bold">{{ post.title }}</h3></a>
                <p class="card-text">{{ post.short_description | safe }}</p>
                <p class="card-text"><small class="text-dark">Posted {{ post.created_on | date:"j M" }}</small></p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-link float-right text-dark font-weight-bold">Read more</a>
              </div>
            </div>
            <div class="col-md-4">
              <img src="{{ post.preview_image.box.url }}" class="card-img" alt="...">
            </div>
          </div>
        </div>
    </div>

  {% elif forloop.last %}
  <div class="container mt-4 bg-latest">
    <div class="row">
     <div class="col align-self-center p-5">
         <h3 class="card-title font-weight-bold">{{ post.title }}</h3>
         <p class="card-text">{{ post.short_description | safe }}</p>
         <a href="{{ post.get_absolute_url }}" class="btn btn-link float-right text-dark font-weight-bold">Read more</a>
      </div>
      <div class="col p-0">
          <img src="{{ post.preview_image.small.url }}" class="img-fluid">
      </div>
    </div>
  </div>

  {% else %}
    {% if forloop.counter0 == 1 %}
      <div class="container mt-4">
        <div class="row">
    {% endif%}

    <div class="col-md-4">
      <div class="card shadow-sm" style="height: 38rem">
          <img src="{{ post.preview_image.box.url }}" class="card-img-top" alt="...">
          <div class="card-body d-flex flex-column">
            <div style="flex: 1 1 auto;">
              <h5 class="card-title font-weight-bold">{{ post.title }}</h5>
              <p class="card-text">{{ post.short_description | safe }}</p>
            </div>
            <a href="{{ post.get_absolute_url }}" class="btn btn-link float-right text-dark font-weight-bold">Read more</a>
          </div>
        </div>
    </div>          

    {% if forloop.counter0 == 3 %}
        </div>
      </div>
    {% endif %}

  {% endif %}

{% endfor %}

<div class="container mt-2">
    <a class="btn btn-more float-right text-light mt-3" href="{% url 'blog.all_posts' %}">See more <i class="ri-arrow-up-circle-fill"></i></a>
</div>


{% endblock %}

templates/blog/new.html
{% extends 'main/base.html' %}


{% block content %} 
<div class="container">
    <form method="post">{% csrf_token %}        
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Post" class="btn btn-primary float-right">
    </form>
</div>
{% endblock %}

templates/blog/post.html
{% extends 'main/base.html' %}


{% block content %} 

<div class="article-section mt-4">
    <div class="container-fluid mt-4" style="background-color: #fafafa">
     <img src="{{ post.preview_image.cropped.url }}" class="mx-auto d-block img-fluid">
    </div>
</div>
<div class="container mt-4">
 {% if user.is_staff %}
 <a href="{% url 'admin:blog_post_change' object_id=post.id %}" class="btn btn-secondary btn-sm active float-right" role="button" aria-pressed="true">edit</a>
 {% endif %}
 <h1 class="font-weight-bold">{{ post.title }}</h1>
 
 <div class="span">
     <h6 class="font-weight-bold">Written by {{ post.author.get_full_name }}</h6>
     <p class="text-secondary ">{{ post.created_on | date:"l M j Y" }}</p>
 </div>
 
    <div class="text-center">
            <p title="Описание поста на языке эмодзи" rel="tooltip"> {{ post.emoji_description }} </p>
    </div>
    <hr>
    <div class="container blog-content">
        {{ post.content | safe }}
    </div>
</div>


{% endblock %}

templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta info -->
    {% if post %}
      <meta name="title" content="{{ post.title }}">
      <meta name="description" content="{{ post.short_description | striptags }}">
      {% if post.keywords %} <meta name="keywords" content="{{ post.keywords }}"> {% endif %}
      <meta property="og:image" content="{{ post.preview_image.small.url }}">
    {% endif  %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.4.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="icon" href="{% static 'main/favicon.ico'%}"  type="image/icon type">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>
      {% if post %}
        {{post.title}}
      {% else %}
        LevLog
      {% endif %}
    </title>

    <script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>


    <script>
        let is_mac = /(Mac|iPhone|iPod|iPad)/i.test(navigator.platform);
        if (!is_mac) {
            window.onload = function() {
              // Parses the document body and    
              // inserts <img> tags in place of Unicode Emojis
              twemoji.parse(document.body,
                      {folder: 'svg', ext: '.svg'}
              );
          }
        }
        
    </script>


  </head>
  <body>
   <!-- NAVIGATION -->
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand font-weight-bold" href="{% url 'levlog.index' %}">
          <img src="{% static 'main/img/levlog_logo.png' %}" class="img-fluid" style="height: 45px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active mr-3">
              <a class="nav-link" href="{% url 'blog.home_view' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'blog.all_posts' %}">Posts</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'blog.random_post' %}">Random post</a>
            </li>
            <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://www.instagram.com/donotshareit/"><i class="ri-instagram-fill"></i></a>
              </li>
            <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://t.me/sevenzing"><i class="ri-telegram-fill"></i></i></a>
              </li>
              <li class="nav-item mt-2 mr-3">
                <a class="text-dark" href="https://github.com/sevenzing/"><i class="ri-github-fill"></i></a>
                
              </li>
          </ul>
        </div>
      </nav>
</div>

   <!-- NAVIGATION END -->
   
    {% block content %}

    {% endblock %}

    <!-- FOOTER -->
    <br><br><br><br><br>

    <footer class="text-center text-white" style="background-color: #f1f1f1;">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.instagram.com/donotshareit/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-instagram-fill"></i
          ></a>

          <!-- Telegram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://t.me/sevenzing"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-telegram-fill"></i
          ></a>

          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://github.com/sevenzing/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="ri-github-fill"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-dark" href="https://levlog.ru/">levlog.ru</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(function () {
            $("[rel='tooltip']").tooltip();
        });
    </script>
  </body>
</html>